server:
  port: 8080
spring:
  datasource:  
    url: jdbc:mysql://localhost:3306/TechnicalTestV2    
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl